apiVersion: v1
kind: Service
metadata:
  name: resultappservice
  labels:
    app: resultappservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    app: resultapppod