apiVersion: v1
kind: Service
metadata:
  name: votingappservice
  labels:
    app: votingappservice
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  type: NodePort
  selector:
    app: votingapppod