apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxreplica
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 5
  template:
    metadata:
        name: nginx
        labels:
            app: nginx
            tier: frontend
    spec:
        containers:
        - name: nginx
          image: nginx
      